### ISSUE TITLE
报错net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by lmk15391997** [ruiyong-lee/wechat-shop-demo#20]
VM1354 asdebug.js:1 GET http://192.168.96.129:7001/weapp/getGoodsWithCategory net::ERR_EMPTY_RESPONSE 
微信小程序打开获取不到商品列表 这个baserul是获取哪的数据的呢

**Comment by ruiyong-lee** [comment]
不好意思，我用我自己的ip地址调试没改回来，你改成localhost:7001就可以了

**Comment by lmk15391997** [comment]
我昨天发现了,解决了已经
